### ISSUE TITLE
Uncaught Jmoo\React\Chrome\Exception\ProtocolErrorException: Invalid parameters

### ISSUE THREAD

**Issue by iorsa** [jmoo/chrome-reactphp#2]
Hello,

I believe this project is kind of outdated, though I thought it should work with some (maybe older) versions of chrome and etc.

I've recently tried to test `pdf-async-reactphp.php` example and with a little modification (added ->done() after promises) I've discovered that it throws:
```
Fatal error: Uncaught Jmoo\React\Chrome\Exception\ProtocolErrorException: Invalid parameters in /root/chrome-reactphp/src/Async/AbstractConnection.php:121
Stack trace:
#0 /root/chrome-reactphp/src/Async/AbstractConnection.php(109): Jmoo\React\Chrome\Async\AbstractConnection->handleProtocolError()
#1 /root/chrome-reactphp/src/Async/AbstractConnection.php(90): Jmoo\React\Chrome\Async\AbstractConnection->handleResponse()
#2 /root/chrome-reactphp/src/Async/Connection.php(30): Jmoo\React\Chrome\Async\AbstractConnection->handleMessage()
#3 /root/chrome-reactphp/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Jmoo\React\Chrome\Async\Connection->Jmoo\React\Chrome\Async\{closure}()
#4 /root/chrome-reactphp/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit()
#5 /root/chrome-reactphp/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}()
#6 /root/chrome-reactphp/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\ in /root/chrome-reactphp/src/Async/AbstractConnection.php on line 121
```

Using latest version of Google Chrome 91.0.4472.164 at debian buster.
Any thoughts?

**Comment by iorsa** [comment]
It was not so hard to find ^_^

In order to use `printToPDF` function you need to specify at least one parameter (for example `Scale`).
So if you update pdf-async-reactphp.php with this lines
```
$printParameters = ['Scale' => 1];
$c->Page->printToPDF($printParameters)->then(...
```
it will work!
